services:
  postgres:
    image: postgres:latest
    container_name: "yanlex-wow-guild-postgres"
    volumes:
      - yanlex-wow-guild-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user-db
      POSTGRES_PASSWORD: user-pw
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.postgresql.rule=HostSNI(`*`)
      - traefik.tcp.routers.postgresql.tls=true
      - traefik.tcp.services.postgresql.loadbalancer.server.port=5432
      - traefik.tcp.routers.postgresql.entrypoints=dbsecure
      - traefik.tcp.routers.postgresql.tls.certresolver=letsencrypt
    networks:
      - wowguild
  frontend:
    image: nginx:stable
    container_name: "yanlex-wow-guild-front-nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./FRONTEND/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./FRONTEND/nginx/index.html:/var/www/dist/index.html
      - ./FRONTEND/public_html:/var/www/dist/kvd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`DOMAIN NAME`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=leresolver"
    networks:
      - wowguild
  traefik:
    image: traefik:v3.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-data:/etc/traefik
      - ./traefik-data/acme.json:/acme.json
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.dbsecure.address=:5432
      - --certificatesresolvers.leresolver.acme.email=YOUR EMAIL
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
    networks:
      - wowguild
  backend:
    build:
      context: ./BACKEND/
      dockerfile: backend.Dockerfile
    image: yanlex-wow-guild-updater:latest
    container_name: "yanlex-wow-guild-updater"
    volumes:
      - yanlex-wow-guild-db-updater:/root/KVD/
    environment:
      DB_NAME: kvd_guild
      GUILD_REGION: eu
      GUILD_REALM: howling-fjord
      GUILD_NAME: "Ключик в дурку"
      DB_USER: user-db
      DB_PASS: user-pw
      DB_NETWORK: wowguild
      DB_ADDRESS: yanlex-wow-guild-postgres
      HOST_DB_PORT: 5432
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`YOUR DOMAIN`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=leresolver"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    networks:
      - wowguild

volumes:
  yanlex-wow-guild-front-nginx:
    name: yanlex-wow-guild-front-nginx
  yanlex-wow-guild-db-updater:
    name: yanlex-wow-guild-db-updater
  yanlex-wow-guild-postgres:
    name: yanlex-wow-guild-postgres

networks:
  wowguild:
    driver: bridge
    external: true
    name: wowguild
