services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      # Дашборд
      - "--api=true"
      - "--api.insecure=false"
      #Logs
      - "--log.level=DEBUG"
      #
      - "--providers.docker=true"
      - "--providers.docker.network=traefik-public"
      - "--providers.docker.exposedbydefault=false"
      # Точки входа
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      #Редирект трафика на https
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      # SSL
      - "--certificatesresolvers.le.acme.email=takashi21@yandex.ru"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    networks:
      - traefik-public
      - wowguild
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.sanyadev.ru`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=yanlex:$$2y$$05$$Bv.yC2MtGc.aex8qwF/O3uCeihnu6l0C90Zk0z4YDKaGpHTUTkCCm"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=le"

  postgres:
    image: postgres:15-alpine
    container_name: "yanlex-wow-guild-postgres"
    volumes:
      - yanlex-wow-guild-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6iuJEsw6iuJEswxv
      POSTGRES_DB: kvd_guild
    expose:
      - 5432
    networks:
      - wowguild

  frontend:
    image: nginx:1.25-alpine
    container_name: "yanlex-wow-guild-front-nginx"
    volumes:
      - ./FRONTEND/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./FRONTEND/public_html:/var/www/dist
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`kvd.sanyadev.ru`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - wowguild

  backend:
    build:
      context: ./BACKEND/
      dockerfile: backend.Dockerfile
    image: yanlex-wow-guild-updater:latest
    container_name: "yanlex-wow-guild-updater"
    depends_on:
      - postgres
    environment:
      DB_NAME: kvd_guild
      DB_USER: postgres
      DB_PASS: 6iuJEsw6iuJEswxv
      DB_ADDRESS: yanlex-wow-guild-postgres
      HOST_DB_PORT: 5432
      GUILD_REGION: eu
      GUILD_REALM: howling-fjord
      GUILD_NAME: "Ключик в дурку"
    expose:
      - 3000
    networks:
      - wowguild
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`kvd.sanyadev.ru`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

  adminer:
    image: adminer
    container_name: "yanlex-wow-guild-adminer"
    networks:
      - wowguild
      - traefik-public
    ports:
      - 8080:8080

volumes:
  yanlex-wow-guild-postgres:
    name: yanlex-wow-guild-postgres
networks:
  wowguild:
    internal: true
  traefik-public:
    external: true
