services:
  postgres:
    image: postgres:15-alpine
    container_name: "yanlex-wow-guild-postgres"
    volumes:
      - yanlex-wow-guild-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6iuJEswxv
      POSTGRES_DB: kvd_guild
    expose:
      - 5432
    networks:
      - wowguild

  adminer:
    image: adminer
    container_name: "yanlex-wow-guild-adminer"
    networks:
      - wowguild
      - traefik-public
    ports:
      - 8080:8080

  frontend:
    image: nginx:1.25-alpine
    container_name: "yanlex-wow-guild-front-nginx"
    volumes:
      - ./FRONTEND/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./FRONTEND/nginx/index.html:/var/www/dist/index.html
      - ./FRONTEND/public_html:/var/www/dist/kvd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`sanyadev.ru`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - wowguild

  traefik:
    image: traefik:v3.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=takashi21@yandex.ru
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    networks:
      - wowguild
      - traefik-public

  backend:
    build:
      context: ./BACKEND/
      dockerfile: backend.Dockerfile
    image: yanlex-wow-guild-updater:latest
    container_name: "yanlex-wow-guild-updater"
    depends_on:
      - postgres
    environment:
      DB_NAME: kvd_guild
      DB_USER: postgres
      DB_PASS: 6iuJEswxv
      DB_ADDRESS: yanlex-wow-guild-postgres
      HOST_DB_PORT: 5432
      GUILD_REGION: eu
      GUILD_REALM: howling-fjord
      GUILD_NAME: "Ключик в дурку"
    expose:
      - 3000
    networks:
      - wowguild
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
        # CORS
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,OPTIONS,PUT,DELETE,PATCH"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=http://yanlex-wow-guild-front-nginx"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"

volumes:
  yanlex-wow-guild-postgres:
    name: yanlex-wow-guild-postgres
networks:
  wowguild:
    internal: true
  traefik-public:
    external: true
